name = "BaslerCamera"
uuid = "e40af120-e25d-11ea-0ce6-f3b09ee65c37"
version = "0.1"
author = ["Paul Thompson"]

[deps]
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"

[compat]
julia = "1"
FFMPEG = "0.2, 0.3, 0.4"
